"""A dependency-free core for automated trading and historical simulation."""

from .clock import Clock, FixedClock, SystemClock
from .domain import (
    AccountId,
    AssetClass,
    ClientOrderId,
    ContractSpec,
    Fill,
    Instrument,
    Money,
    Order,
    OrderId,
    OrderRequest,
    OrderStatus,
    OrderType,
    Portfolio,
    PortfolioSnapshot,
    Position,
    Side,
    TimeInForce,
    TradeId,
)
from .errors import (
    BrokerError,
    ConfigurationError,
    DuplicateRequestError,
    MarketDataError,
    OrderStateError,
    RiskRejectedError,
    TradingEngineError,
    ValidationError,
)
from .catalog import InstrumentCatalog
from .config import BrokerSettings, EngineSettings, load_settings
from .market import Bar, MarketDataStore, Quote, TradeTick
from .risk import CircuitBreaker, RiskDecision, RiskEngine, RiskLimits
from .execution import ExecutionService, OrderRepository, SimulatedBroker
from .strategy import (
    BreakoutStrategy,
    FixedQuantitySizer,
    MovingAverageCrossStrategy,
    Signal,
    SignalAction,
    StrategyRunner,
)
from .backtest import BacktestReport, BacktestRunner, HistoricalFeed

__all__ = [
    "AccountId",
    "AssetClass",
    "BacktestReport",
    "BacktestRunner",
    "Bar",
    "BrokerError",
    "BrokerSettings",
    "BreakoutStrategy",
    "CircuitBreaker",
    "ClientOrderId",
    "Clock",
    "ConfigurationError",
    "ContractSpec",
    "DuplicateRequestError",
    "EngineSettings",
    "ExecutionService",
    "Fill",
    "FixedClock",
    "FixedQuantitySizer",
    "HistoricalFeed",
    "Instrument",
    "InstrumentCatalog",
    "MarketDataError",
    "MarketDataStore",
    "Money",
    "MovingAverageCrossStrategy",
    "Order",
    "OrderId",
    "OrderRepository",
    "OrderRequest",
    "OrderStateError",
    "OrderStatus",
    "OrderType",
    "Portfolio",
    "PortfolioSnapshot",
    "Position",
    "Quote",
    "RiskDecision",
    "RiskEngine",
    "RiskLimits",
    "RiskRejectedError",
    "Side",
    "Signal",
    "SignalAction",
    "SimulatedBroker",
    "StrategyRunner",
    "SystemClock",
    "TimeInForce",
    "TradeId",
    "TradeTick",
    "TradingEngineError",
    "ValidationError",
    "load_settings",
]
