# TrueData values
REALTIME_PORT = 8082
HISTORY_PORT = 8092
USERNAME = "FYERS1201"
PASSWORD = "4jV4JgKB"

# bnfutures_data
BN_FUTURES_CONTRACT = "NSE:" + "BANKNIFTY21DECFUT"
BN_FUTURES_CONTRACT_FETCH_VALUES = "BANKNIFTY21DECFUT"