# Generated by Django 3.2.4 on 2021-06-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankniftybot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlotsinput',
            name='order_code_list',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userlotsinput',
            name='order_id_list',
            field=models.TextField(null=True),
        ),
    ]
