# Generated by Django 3.2.4 on 2021-06-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankniftybot', '0002_auto_20210621_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlotsinput',
            name='order_code_list',
        ),
        migrations.RemoveField(
            model_name='userlotsinput',
            name='order_id_list',
        ),
        migrations.AddField(
            model_name='userlotsinput',
            name='order_closing_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userlotsinput',
            name='order_id_1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userlotsinput',
            name='order_id_2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userlotsinput',
            name='p_and_l',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userlotsinput',
            name='stock',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userlotsinput',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
