# Generated by Django 3.2.5 on 2021-07-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankniftybot', '0003_auto_20210628_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlotsinput',
            name='fyers_id',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userlotsinput',
            name='fyers_pan_dob',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userlotsinput',
            name='fyers_password',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userlotsinput',
            name='stock',
            field=models.CharField(choices=[('BANKNIFTY21JULFUT', 'BANKNIFTY21JULFUT'), ('BANKNIFTY21AUGFUT', 'BANKNIFTY21AUGFUT')], max_length=300, null=True),
        ),
    ]
