# Generated by Django 3.2.5 on 2021-08-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankniftybot', '0004_auto_20210719_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlotsinput',
            name='stock',
            field=models.CharField(choices=[('BANKNIFTY21AUGFUT', 'BANKNIFTY21AUGFUT')], max_length=300, null=True),
        ),
    ]
