# Generated by Django 3.2.9 on 2022-02-05 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BNOptionsBotOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dummy_id', models.IntegerField(default=1)),
                ('order_value', models.IntegerField()),
                ('contract', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionsOrdersDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=500)),
                ('code', models.IntegerField()),
                ('message', models.CharField(max_length=1000, null=True)),
                ('is_active', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
