# TrueData values
REALTIME_PORT = 8082
HISTORY_PORT = 8092
USERNAME = "FYERS1201"
PASSWORD = "4jV4JgKB"

# bnfutures_data
BANKNIFTY_OPTIONS_CONTRACT_YEAR_MONTH_DATE = "NSE:BANKNIFTY" + "22" + "2" + "10"
OPTIONS_DEPTH = 500