# Generated by Django 3.2.5 on 2021-08-07 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyers', '0002_usersubscriptionrelation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscriptionrelation',
            old_name='user',
            new_name='user_id',
        ),
    ]
