# Generated by Django 3.2.5 on 2021-08-08 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fyers', '0003_rename_user_usersubscriptionrelation_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBankniftyFyersRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('stock', models.CharField(choices=[('BANKNIFTY21AUGFUT', 'BANKNIFTY21AUGFUT')], max_length=300, null=True)),
                ('number_of_lots', models.IntegerField()),
                ('order_id_1', models.CharField(max_length=300, null=True)),
                ('order_id_2', models.CharField(max_length=300, null=True)),
                ('order_closing_type', models.CharField(max_length=50, null=True)),
                ('value', models.IntegerField(null=True)),
                ('p_and_l', models.IntegerField(null=True)),
                ('fyers_id', models.CharField(max_length=300, null=True)),
                ('fyers_password', models.CharField(max_length=300, null=True)),
                ('fyers_pan_dob', models.CharField(max_length=300, null=True)),
                ('trading_platform', models.CharField(max_length=300, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCrudeoilFyersRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('stock', models.CharField(choices=[('BANKNIFTY21AUGFUT', 'BANKNIFTY21AUGFUT')], max_length=300, null=True)),
                ('number_of_lots', models.IntegerField()),
                ('order_id', models.CharField(max_length=300, null=True)),
                ('value', models.IntegerField(null=True)),
                ('p_and_l', models.IntegerField(null=True)),
                ('fyers_id', models.CharField(max_length=300, null=True)),
                ('fyers_password', models.CharField(max_length=300, null=True)),
                ('fyers_pan_dob', models.CharField(max_length=300, null=True)),
                ('trading_platform', models.CharField(max_length=300, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserLotsInput',
        ),
    ]
