# Generated by Django 3.2.5 on 2021-08-11 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyers', '0005_userfyersapprelation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfyersapprelation',
            old_name='user_id',
            new_name='user',
        ),
    ]
