# Generated by Django 3.2.5 on 2021-08-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyers', '0006_rename_user_id_userfyersapprelation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscriptionrelation',
            old_name='subscription_date',
            new_name='date_added',
        ),
        migrations.AddField(
            model_name='usersubscriptionrelation',
            name='last_subscription_date',
            field=models.DateTimeField(null=True),
        ),
    ]
