# Generated by Django 3.2.5 on 2021-08-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyers', '0007_auto_20210815_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscriptionrelation',
            old_name='user_id',
            new_name='user',
        ),
    ]
