# Generated by Django 3.2.5 on 2021-08-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyers', '0008_rename_user_id_usersubscriptionrelation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbankniftyfyersrelation',
            name='fyers_id',
        ),
        migrations.RemoveField(
            model_name='userbankniftyfyersrelation',
            name='fyers_pan_dob',
        ),
        migrations.RemoveField(
            model_name='userbankniftyfyersrelation',
            name='fyers_password',
        ),
        migrations.RemoveField(
            model_name='userbankniftyfyersrelation',
            name='order_closing_type',
        ),
        migrations.RemoveField(
            model_name='userbankniftyfyersrelation',
            name='order_id_1',
        ),
        migrations.RemoveField(
            model_name='userbankniftyfyersrelation',
            name='order_id_2',
        ),
        migrations.RemoveField(
            model_name='userbankniftyfyersrelation',
            name='p_and_l',
        ),
        migrations.RemoveField(
            model_name='userbankniftyfyersrelation',
            name='trading_platform',
        ),
        migrations.RemoveField(
            model_name='userbankniftyfyersrelation',
            name='value',
        ),
        migrations.RemoveField(
            model_name='usercrudeoilfyersrelation',
            name='fyers_id',
        ),
        migrations.RemoveField(
            model_name='usercrudeoilfyersrelation',
            name='fyers_pan_dob',
        ),
        migrations.RemoveField(
            model_name='usercrudeoilfyersrelation',
            name='fyers_password',
        ),
        migrations.RemoveField(
            model_name='usercrudeoilfyersrelation',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='usercrudeoilfyersrelation',
            name='p_and_l',
        ),
        migrations.RemoveField(
            model_name='usercrudeoilfyersrelation',
            name='trading_platform',
        ),
        migrations.RemoveField(
            model_name='usercrudeoilfyersrelation',
            name='value',
        ),
        migrations.AddField(
            model_name='userbankniftyfyersrelation',
            name='fyers_access_token',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='usercrudeoilfyersrelation',
            name='fyers_access_token',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
