# Generated by Django 3.2.5 on 2021-10-03 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fyers', '0010_userintradaystraddlerelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBNOptionsBuyingFyersRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('stock', models.CharField(choices=[('BANKNIFTY21AUGFUT', 'BANKNIFTY21AUGFUT')], max_length=300, null=True)),
                ('number_of_lots', models.IntegerField()),
                ('fyers_access_token', models.CharField(max_length=300, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
