# Generated by Django 3.2.9 on 2022-02-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BNFuturesBotOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dummy_id', models.IntegerField(default=1)),
                ('order_value_1', models.IntegerField()),
                ('side_1', models.IntegerField()),
                ('difference_1', models.IntegerField()),
                ('order_value_2', models.IntegerField()),
                ('side_2', models.IntegerField()),
                ('difference_2', models.IntegerField()),
            ],
        ),
    ]
